server:
  port: 33400

general:
  kafka-topic: transactions_topic

spring:
  kafka: { bootstrap-servers: localhost:9092 }

  main:
    allow-bean-definition-overriding: true

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration

logging:
  level:
    root: INFO